# Generated by Django 4.2.11 on 2024-03-30 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminStaff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentMaintenance",
            fields=[
                ("equipment_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("last_maintenance_date", models.DateField()),
                ("next_maintenance_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=255)),
                ("room_id", models.IntegerField()),
                ("schedule", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("fitness_goal", models.CharField(blank=True, max_length=255)),
                ("health_metrics", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_id", models.IntegerField()),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                ("trainer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("availability", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("bill_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.member"
                    ),
                ),
            ],
        ),
    ]
