# Generated by Django 4.2.11 on 2024-04-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="email",),
    ]
