# Generated by Django 5.0.3 on 2024-04-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='act_levels',
            field=models.CharField(blank=True, max_length=255, verbose_name='Activity Levels'),
        ),
    ]
