# Generated by Django 4.2.11 on 2024-04-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="availability",
            field=models.JSONField(null=True),
        ),
    ]
