# Generated by Django 4.2.11 on 2024-04-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="diastolic_bp",
            field=models.IntegerField(
                null=True, verbose_name="Diastolic Blood Pressure"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="systolic_bp",
            field=models.IntegerField(
                null=True, verbose_name="Systolic Blood Pressure"
            ),
        ),
    ]
