# Generated by Django 4.2.11 on 2024-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentmaintenance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_MAINTENANCE", "In Maintenance"),
                    ("BROKEN", "Broken"),
                    ("FUNCTIONING", "Functioning"),
                ],
                default="FUNCTIONING",
                max_length=15,
            ),
        ),
        migrations.DeleteModel(name="Billing",),
    ]
