# Generated by Django 5.0.3 on 2024-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='act_levels',
            field=models.CharField(blank=True, default='1-3 x times a week', max_length=255, null=True, verbose_name='Activity Levels'),
        ),
    ]
