# Generated by Django 4.2.11 on 2024-04-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_member_diastolic_bp_alter_member_systolic_bp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="act_levels",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Activity Levels"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="fitness_goal",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Fitness Goal"
            ),
        ),
    ]
