# Generated by Django 4.2.11 on 2024-04-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_trainer_availability_traineravailiblity"),
    ]

    operations = [
        migrations.DeleteModel(name="TrainerAvailiblity",),
    ]
