# Generated by Django 5.0.3 on 2024-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, default=20, max_digits=3, null=True),
        ),
    ]
