-- Start with the basic entities with no dependencies
CREATE TABLE IF NOT EXISTS public.myapp_admin
(
    admin_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT myapp_admin_pkey PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public.myapp_room
(
    room_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    CONSTRAINT myapp_room_pkey PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public.myapp_member
(
    member_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    health_metrics jsonb NOT NULL,
    height numeric(5,2),
    weight numeric(5,2),
    goal_weight numeric(5,2),
    weeks_to_goal integer,
    diastolic_bp integer,
    systolic_bp integer,
    fitness_goal character varying(255),
    act_levels character varying(255),
    age numeric(3,0),
    CONSTRAINT myapp_member_pkey PRIMARY KEY (member_id)
);

CREATE TABLE IF NOT EXISTS public.myapp_trainer
(
    trainer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT myapp_trainer_pkey PRIMARY KEY (trainer_id)
);

-- Tables that depend on existing entities
CREATE TABLE IF NOT EXISTS public.myapp_billing
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount_due numeric(10,2) NOT NULL,
    due_date date NOT NULL,
    status character varying(20) NOT NULL,
    member_id integer NOT NULL,
    CONSTRAINT myapp_billing_pkey PRIMARY KEY (id),
    CONSTRAINT myapp_billing_member_id_fk FOREIGN KEY (member_id)
        REFERENCES public.myapp_member (member_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_traineravailability
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_of_week integer NOT NULL,
    check_in time without time zone NOT NULL,
    check_out time without time zone NOT NULL,
    trainer_id integer NOT NULL,
    CONSTRAINT myapp_traineravailability_pkey PRIMARY KEY (id),
    CONSTRAINT myapp_traineravailability_trainer_id_fk FOREIGN KEY (trainer_id)
        REFERENCES public.myapp_trainer (trainer_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_personalsession
(
    personal_session_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    member_id integer NOT NULL,
    trainer_id integer NOT NULL,
    CONSTRAINT myapp_personalsession_pkey PRIMARY KEY (personal_session_id),
    CONSTRAINT myapp_personalsession_member_id_fk FOREIGN KEY (member_id)
        REFERENCES public.myapp_member (member_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT myapp_personalsession_trainer_id_fk FOREIGN KEY (trainer_id)
        REFERENCES public.myapp_trainer (trainer_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_groupfitnessclass
(
    group_fitness_class_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    room_id integer NOT NULL,
    trainer_id integer NOT NULL,
    CONSTRAINT myapp_groupfitnessclass_pkey PRIMARY KEY (group_fitness_class_id),
    CONSTRAINT myapp_groupfitnessclass_trainer_id_fk FOREIGN KEY (trainer_id)
        REFERENCES public.myapp_trainer (trainer_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT myapp_groupfitnessclass_room_id_fk FOREIGN KEY (room_id)
        REFERENCES public.myapp_room (room_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_membergroupfitnessregistration
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    registration_date date NOT NULL,
    group_fitness_class_id integer NOT NULL,
    member_id integer NOT NULL,
    CONSTRAINT myapp_membergroupfitnessregistration_pkey PRIMARY KEY (id),
    CONSTRAINT myapp_membergroupfitnessregistration_group_fitness_class_id_fk FOREIGN KEY (group_fitness_class_id)
        REFERENCES public.myapp_groupfitnessclass (group_fitness_class_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT myapp_membergroupfitnessregistration_member_id_fk FOREIGN KEY (member_id)
        REFERENCES public.myapp_member (member_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_payment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    payment_date date NOT NULL,
    payment_method character varying(50) NOT NULL,
    payment_status character varying(20) NOT NULL,
    billing_id bigint NOT NULL,
    CONSTRAINT myapp_payment_pkey PRIMARY KEY (id),
    CONSTRAINT myapp_payment_billing_id_fk FOREIGN KEY (billing_id)
        REFERENCES public.myapp_billing (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_roombooking
(
    room_booking_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    room_id integer NOT NULL,
    CONSTRAINT myapp_roombooking_pkey PRIMARY KEY (room_booking_id),
    CONSTRAINT myapp_roombooking_room_id_fk FOREIGN KEY (room_id)
        REFERENCES public.myapp_room (room_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.myapp_service
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    service_name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    CONSTRAINT myapp_service_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.myapp_equipmentmaintenance
(
    equipment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    last_maintenance_date date NOT NULL,
    next_maintenance_date date NOT NULL,
    status character varying(15) NOT NULL,
    CONSTRAINT myapp_equipmentmaintenance_pkey PRIMARY KEY (equipment_id)
);
