-- A BUNCH OF SAMPLE INFO TO BE INSERTED TO THE DATABASE GENERATED BY CHAT GPT

-- Insert sample Members
INSERT INTO members (name, email, password, fitness_goal) VALUES
('John Doe', 'john.doe@example.com', 'password123', 'Lose weight'),
('Jane Smith', 'jane.smith@example.com', 'password123', 'Build muscle');

-- Insert sample Trainers
INSERT INTO trainers (name, availability) VALUES
('Alex Trainer', '{"Monday": ["09:00", "17:00"], "Wednesday": ["09:00", "17:00"]}'),
('Sam Coach', '{"Tuesday": ["10:00", "18:00"], "Thursday": ["10:00", "18:00"]}');

-- Insert sample Admin Staff
INSERT INTO admin_staff (name) VALUES
('Alice Admin'),
('Bob Manager');

-- Insert sample Fitness Classes
INSERT INTO fitness_classes (class_name, room_id, schedule) VALUES
('Yoga', 101, '2024-04-05 08:00:00+00'),
('High-Intensity Interval Training', 102, '2024-04-06 09:00:00+00');

-- Insert sample Room Bookings
INSERT INTO room_bookings (room_id, booking_date, start_time, end_time) VALUES
(101, '2024-04-05', '08:00', '09:00'),
(102, '2024-04-06', '09:00', '10:00');

-- Insert sample Equipment Maintenance records
INSERT INTO equipment_maintenance (name, last_maintenance_date, next_maintenance_date) VALUES
('Treadmill #1', '2024-03-01', '2024-06-01'),
('Elliptical #1', '2024-02-15', '2024-05-15');

-- Insert sample Billing records
INSERT INTO billing (member_id, amount, paid, payment_date) VALUES
(1, 50.00, TRUE, '2024-03-10'),
(2, 75.00, FALSE, NULL);
